"""ADIv5 — ARM Debug Interface v5 sobre SWD."""

from core.adiv5.adiv5 import ADIv5, DebugPowerError
from core.adiv5.constants import (
    AIRCR,
    AIRCR_SYSRESETREQ,
    AIRCR_VECTKEY,
    CTRL_CDBGPWRUPACK,
    CTRL_CDBGPWRUPREQ,
    CTRL_CSYSPWRUPACK,
    CTRL_CSYSPWRUPREQ,
    DCRDR,
    DCRSR,
    DCRSR_REGWNR,
    DHCSR,
    DHCSR_C_DEBUGEN,
    DHCSR_C_HALT,
    DHCSR_C_STEP,
    DHCSR_DBGKEY,
    DHCSR_S_HALT,
    DHCSR_S_LOCKUP,
    DHCSR_S_REGRDY,
    REG_LR,
    REG_PC,
    REG_R0,
    REG_R1,
    REG_R12,
    REG_SP,
    REG_XPSR,
)

__all__ = [
    "AIRCR",
    "AIRCR_SYSRESETREQ",
    "AIRCR_VECTKEY",
    "CTRL_CDBGPWRUPACK",
    "CTRL_CDBGPWRUPREQ",
    "CTRL_CSYSPWRUPACK",
    "CTRL_CSYSPWRUPREQ",
    "DCRDR",
    "DCRSR",
    "DCRSR_REGWNR",
    "DHCSR",
    "DHCSR_C_DEBUGEN",
    "DHCSR_C_HALT",
    "DHCSR_C_STEP",
    "DHCSR_DBGKEY",
    "DHCSR_S_HALT",
    "DHCSR_S_LOCKUP",
    "DHCSR_S_REGRDY",
    "REG_LR",
    "REG_PC",
    "REG_R0",
    "REG_R1",
    "REG_R12",
    "REG_SP",
    "REG_XPSR",
    "ADIv5",
    "DebugPowerError",
]
